//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""GameMap"",
            ""id"": ""ff1c1849-e7c3-4bed-850f-6cf786b056c2"",
            ""actions"": [
                {
                    ""name"": ""Thrust"",
                    ""type"": ""PassThrough"",
                    ""id"": ""98d1265a-cfe3-4cd1-b4db-5dad5cbfe823"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""69edc8ab-5e2e-405d-a871-fb03604d344c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Invert"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""89e34f80-a454-46ff-8ca5-c633ce0722b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7ec00f8e-1524-4c7f-a08a-03ec55cf2f8f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f253796e-e485-48f2-863e-8dd42653c03f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thrust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""0d8b3e44-4f26-4dcc-97be-57ee522b88e9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2da88d6c-c765-4fb4-9de5-c3665fb19f55"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""41767365-28e4-413b-ba91-44097ec18e96"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""31389075-4b7b-48c0-aa02-4ceb00fd2020"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1de717be-c4e0-46eb-a0c0-799ac18ed4e1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CheatMap"",
            ""id"": ""5440d4db-3b65-4c30-a412-a69d628e38dc"",
            ""actions"": [
                {
                    ""name"": ""NextLevel"",
                    ""type"": ""Button"",
                    ""id"": ""5fab6e27-9509-41e8-ad37-987d8eb8a1e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisableCollisions"",
                    ""type"": ""Button"",
                    ""id"": ""1fa3c7ce-9fd5-4bef-8126-502ec645d354"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0cad89de-b95a-4eb7-8778-51213b8e8182"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa14af92-b534-459e-8525-d7ead35aeb78"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisableCollisions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameMap
        m_GameMap = asset.FindActionMap("GameMap", throwIfNotFound: true);
        m_GameMap_Thrust = m_GameMap.FindAction("Thrust", throwIfNotFound: true);
        m_GameMap_Rotate = m_GameMap.FindAction("Rotate", throwIfNotFound: true);
        m_GameMap_Quit = m_GameMap.FindAction("Quit", throwIfNotFound: true);
        // CheatMap
        m_CheatMap = asset.FindActionMap("CheatMap", throwIfNotFound: true);
        m_CheatMap_NextLevel = m_CheatMap.FindAction("NextLevel", throwIfNotFound: true);
        m_CheatMap_DisableCollisions = m_CheatMap.FindAction("DisableCollisions", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameMap
    private readonly InputActionMap m_GameMap;
    private IGameMapActions m_GameMapActionsCallbackInterface;
    private readonly InputAction m_GameMap_Thrust;
    private readonly InputAction m_GameMap_Rotate;
    private readonly InputAction m_GameMap_Quit;
    public struct GameMapActions
    {
        private @Controls m_Wrapper;
        public GameMapActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Thrust => m_Wrapper.m_GameMap_Thrust;
        public InputAction @Rotate => m_Wrapper.m_GameMap_Rotate;
        public InputAction @Quit => m_Wrapper.m_GameMap_Quit;
        public InputActionMap Get() { return m_Wrapper.m_GameMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameMapActions set) { return set.Get(); }
        public void SetCallbacks(IGameMapActions instance)
        {
            if (m_Wrapper.m_GameMapActionsCallbackInterface != null)
            {
                @Thrust.started -= m_Wrapper.m_GameMapActionsCallbackInterface.OnThrust;
                @Thrust.performed -= m_Wrapper.m_GameMapActionsCallbackInterface.OnThrust;
                @Thrust.canceled -= m_Wrapper.m_GameMapActionsCallbackInterface.OnThrust;
                @Rotate.started -= m_Wrapper.m_GameMapActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_GameMapActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_GameMapActionsCallbackInterface.OnRotate;
                @Quit.started -= m_Wrapper.m_GameMapActionsCallbackInterface.OnQuit;
                @Quit.performed -= m_Wrapper.m_GameMapActionsCallbackInterface.OnQuit;
                @Quit.canceled -= m_Wrapper.m_GameMapActionsCallbackInterface.OnQuit;
            }
            m_Wrapper.m_GameMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Thrust.started += instance.OnThrust;
                @Thrust.performed += instance.OnThrust;
                @Thrust.canceled += instance.OnThrust;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Quit.started += instance.OnQuit;
                @Quit.performed += instance.OnQuit;
                @Quit.canceled += instance.OnQuit;
            }
        }
    }
    public GameMapActions @GameMap => new GameMapActions(this);

    // CheatMap
    private readonly InputActionMap m_CheatMap;
    private ICheatMapActions m_CheatMapActionsCallbackInterface;
    private readonly InputAction m_CheatMap_NextLevel;
    private readonly InputAction m_CheatMap_DisableCollisions;
    public struct CheatMapActions
    {
        private @Controls m_Wrapper;
        public CheatMapActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @NextLevel => m_Wrapper.m_CheatMap_NextLevel;
        public InputAction @DisableCollisions => m_Wrapper.m_CheatMap_DisableCollisions;
        public InputActionMap Get() { return m_Wrapper.m_CheatMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CheatMapActions set) { return set.Get(); }
        public void SetCallbacks(ICheatMapActions instance)
        {
            if (m_Wrapper.m_CheatMapActionsCallbackInterface != null)
            {
                @NextLevel.started -= m_Wrapper.m_CheatMapActionsCallbackInterface.OnNextLevel;
                @NextLevel.performed -= m_Wrapper.m_CheatMapActionsCallbackInterface.OnNextLevel;
                @NextLevel.canceled -= m_Wrapper.m_CheatMapActionsCallbackInterface.OnNextLevel;
                @DisableCollisions.started -= m_Wrapper.m_CheatMapActionsCallbackInterface.OnDisableCollisions;
                @DisableCollisions.performed -= m_Wrapper.m_CheatMapActionsCallbackInterface.OnDisableCollisions;
                @DisableCollisions.canceled -= m_Wrapper.m_CheatMapActionsCallbackInterface.OnDisableCollisions;
            }
            m_Wrapper.m_CheatMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @NextLevel.started += instance.OnNextLevel;
                @NextLevel.performed += instance.OnNextLevel;
                @NextLevel.canceled += instance.OnNextLevel;
                @DisableCollisions.started += instance.OnDisableCollisions;
                @DisableCollisions.performed += instance.OnDisableCollisions;
                @DisableCollisions.canceled += instance.OnDisableCollisions;
            }
        }
    }
    public CheatMapActions @CheatMap => new CheatMapActions(this);
    public interface IGameMapActions
    {
        void OnThrust(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnQuit(InputAction.CallbackContext context);
    }
    public interface ICheatMapActions
    {
        void OnNextLevel(InputAction.CallbackContext context);
        void OnDisableCollisions(InputAction.CallbackContext context);
    }
}
